"""
Coffee Shop Sales Analysis
==========================
Author : Badger-analyst
Dataset: data/sales_data.csv  (generated by generate_data.py)
Period : January – March 2023

Run:
    python analysis.py

Outputs:
    - Printed metrics summary to terminal
    - images/monthly_sales.png
    - images/top_items_revenue.png
    - images/daily_sales_trend.png
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# ── 0. Setup ─────────────────────────────────────────────────────────────────
os.makedirs("images", exist_ok=True)  # Ensure images folder exists

# ── 1. Load & Parse ───────────────────────────────────────────────────────────
df = pd.read_csv("data/sales_data.csv")
df["Date"] = pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.to_period("M")

print("=" * 50)
print("  COFFEE SHOP SALES ANALYSIS — Jan–Mar 2023")
print("=" * 50)

# ── 2. Data Cleaning ──────────────────────────────────────────────────────────
original_rows = len(df)
df = df[df["Total"] > 0]                   # Remove voided / invalid transactions
df = df.dropna(subset=["Item", "Total"])   # Drop rows missing key fields
cleaned_rows = len(df)

print(f"\n[Data Quality]")
print(f"  Rows loaded   : {original_rows:,}")
print(f"  Rows removed  : {original_rows - cleaned_rows:,}")
print(f"  Rows analysed : {cleaned_rows:,}")

# ── 3. Revenue Overview ───────────────────────────────────────────────────────
total_revenue = df["Total"].sum()
total_transactions = len(df)
avg_transaction_value = df["Total"].mean()

print(f"\n[Revenue Overview]")
print(f"  Total Revenue         : ${total_revenue:,.2f}")
print(f"  Total Transactions    : {total_transactions:,}")
print(f"  Avg Transaction Value : ${avg_transaction_value:.2f}")

# ── 4. Monthly Sales ──────────────────────────────────────────────────────────
monthly_sales = df.groupby("Month")["Total"].sum()
monthly_sales.index = monthly_sales.index.astype(str)

print(f"\n[Monthly Revenue]")
for month, rev in monthly_sales.items():
    pct = (rev / total_revenue) * 100
    print(f"  {month} : ${rev:,.2f}  ({pct:.1f}% of total)")

# Plot — Monthly Sales Bar Chart
fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(monthly_sales.index, monthly_sales.values, color=["#6F4E37", "#A0522D", "#D2691E"], edgecolor="white")
ax.set_title("Monthly Revenue — Jan to Mar 2023", fontsize=14, fontweight="bold", pad=15)
ax.set_ylabel("Total Revenue ($)")
ax.set_xlabel("Month")
for bar in bars:
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 100,
            f"${bar.get_height():,.0f}", ha="center", va="bottom", fontsize=10)
ax.set_ylim(0, monthly_sales.max() * 1.15)
plt.tight_layout()
plt.savefig("images/monthly_sales.png", dpi=150)
plt.close()
print("\n  ✓ Chart saved: images/monthly_sales.png")

# ── 5. Top Items by Revenue ───────────────────────────────────────────────────
item_revenue = df.groupby("Item")["Total"].sum().sort_values(ascending=False)

print(f"\n[Top Items by Revenue]")
for item, rev in item_revenue.items():
    pct = (rev / total_revenue) * 100
    print(f"  {item:<15} ${rev:>8,.2f}  ({pct:.1f}%)")

# Plot — Top 5 Pie Chart
top5 = item_revenue.head(5)
colours = ["#6F4E37", "#A0522D", "#D2691E", "#CD853F", "#DEB887"]
fig, ax = plt.subplots(figsize=(8, 6))
wedges, texts, autotexts = ax.pie(
    top5.values,
    labels=top5.index,
    autopct="%1.1f%%",
    colors=colours,
    startangle=140,
    pctdistance=0.82
)
for text in autotexts:
    text.set_fontsize(9)
ax.set_title("Top 5 Items by Revenue — Jan to Mar 2023", fontsize=13, fontweight="bold", pad=20)
plt.tight_layout()
plt.savefig("images/top_items_revenue.png", dpi=150)
plt.close()
print("  ✓ Chart saved: images/top_items_revenue.png")

# ── 6. Top Items by Quantity ──────────────────────────────────────────────────
item_qty = df.groupby("Item")["Quantity"].sum().sort_values(ascending=False)

print(f"\n[Top Items by Units Sold]")
for item, qty in item_qty.items():
    print(f"  {item:<15} {qty:>6,} units")

# ── 7. Daily Sales Analysis ───────────────────────────────────────────────────
daily_sales = df.groupby("Date")["Total"].sum()
avg_daily = daily_sales.mean()
peak_day = daily_sales.idxmax()
slow_day = daily_sales.idxmin()

print(f"\n[Daily Sales]")
print(f"  Average Daily Revenue : ${avg_daily:.2f}")
print(f"  Peak Day              : {peak_day.date()}  —  ${daily_sales.max():,.2f}")
print(f"  Slowest Day           : {slow_day.date()}  —  ${daily_sales.min():,.2f}")
print(f"  Peak vs Slowest Ratio : {daily_sales.max() / daily_sales.min():.1f}x")

# Plot — Daily Sales Trend Line
fig, ax = plt.subplots(figsize=(12, 5))
ax.plot(daily_sales.index, daily_sales.values, color="#6F4E37", linewidth=1.2, alpha=0.85)
ax.fill_between(daily_sales.index, daily_sales.values, alpha=0.15, color="#A0522D")

# Annotate peak and slowest
ax.annotate(f"Peak: ${daily_sales.max():,.0f}\n{peak_day.date()}",
            xy=(peak_day, daily_sales.max()),
            xytext=(10, -30), textcoords="offset points",
            arrowprops=dict(arrowstyle="->", color="green"),
            color="green", fontsize=8)
ax.annotate(f"Slowest: ${daily_sales.min():,.0f}\n{slow_day.date()}",
            xy=(slow_day, daily_sales.min()),
            xytext=(10, 20), textcoords="offset points",
            arrowprops=dict(arrowstyle="->", color="red"),
            color="red", fontsize=8)

ax.set_title("Daily Revenue Trend — Jan to Mar 2023", fontsize=14, fontweight="bold", pad=15)
ax.set_ylabel("Revenue ($)")
ax.set_xlabel("Date")
plt.tight_layout()
plt.savefig("images/daily_sales_trend.png", dpi=150)
plt.close()
print("  ✓ Chart saved: images/daily_sales_trend.png")

# ── 8. Final Summary ──────────────────────────────────────────────────────────
print("\n" + "=" * 50)
print("  SUMMARY")
print("=" * 50)
print(f"  Total Revenue     : ${total_revenue:,.2f}")
print(f"  Best Month        : {monthly_sales.idxmax()}  (${monthly_sales.max():,.2f})")
print(f"  #1 Item (Revenue) : {item_revenue.index[0]}  (${item_revenue.iloc[0]:,.2f})")
print(f"  #1 Item (Volume)  : {item_qty.index[0]}  ({item_qty.iloc[0]:,} units)")
print(f"  Peak Day          : {peak_day.date()}  (${daily_sales.max():,.2f})")
print("=" * 50)
print("\n  All charts saved to images/")
